Fix Xcode 14.3 which supports only iOS 11.0+
zxingify/zxingify-objc pull request #575
Opened 2023-04-08 22:26 UTC by kenstir

2023-06-29 18:34 UTC, joeydong approved these changes

2023-07-24 13:04 UTC, KBEMobisys commented
@kenstir I think the [README.md](https://github.com/zxingify/zxingify-objc#readme) should also be updated, right?
Anyway, it would be very cool if we could merge this back and release a new version in CocoaPods.

2023-07-31 12:43 UTC, KBEMobisys commented on ZXingObjC/client/ZXCapture.m
> +  AVCaptureDeviceDiscoverySession *captureDeviceDiscoverySession = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
This change is only available on macOS 10.15 or never. So for MacOS we would have to increase the deployment target to '10.15'. To stay as compatible as possible I would advise to drop this change again until "AVCaptureDevice" is really removed.

2023-07-31 12:58 UTC, KBEMobisys commented on ZXingObjC/client/ZXCapture.m
> +  AVCaptureDeviceDiscoverySession *captureDeviceDiscoverySession = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
OK, message "'devicesWithMediaType:' is deprecated: first deprecated in iOS 10.0 - Use AVCaptureDeviceDiscoverySession instead." is an error and not a warning. So, then we have two options:
- Set build setting "Treat Warnings as Errors" to No
- Set deployment target of MacOS to 10.15

2023-07-31 13:05 UTC, KBEMobisys requested changes
One of the changes is breaking target "OS X". See other comments

2023-08-01 00:51 UTC, kenstir commented on ZXingObjC/client/ZXCapture.m
> +  AVCaptureDeviceDiscoverySession *captureDeviceDiscoverySession = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
My understanding is that it is deprecated in iOS 10 and *removed* in iOS 11.  And since Xcode 14.3 supports only iOS 11.0+, the "Treat Warnings as Error"=no option is not viable.

Sorry I didn't catch the macOS regression, I use only iOS builds.  Let me see if I can amend this PR to increase the deployment target on macOS.  At least then this PR will be a potential option to move forward.

2023-08-01 02:17 UTC, kenstir commented on ZXingObjC/client/ZXCapture.m
> +  AVCaptureDeviceDiscoverySession *captureDeviceDiscoverySession = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
I updated the deployment target to 10.15, and now it is building and unit tests passing on Xcode 14.3.1.

2023-08-01 02:19 UTC, kenstir commented
> One of the changes is breaking target "OS X". See other comments

The osx target and its unit tests are passing, now that I updated the deployment  target to 10.15.  Also I updated the README to indicate the new base level.

2023-08-01 07:22 UTC, KBEMobisys commented on ZXingObjC/client/ZXCapture.m
> +  AVCaptureDeviceDiscoverySession *captureDeviceDiscoverySession = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
Thanks for fixing MacOS :) 

"devicesWithMediaType:" is introduced in iOS 4.0 and first deprecated in iOS 10.0. It is still available in iOS 11 and later. It's only deprecated so far. See https://developer.apple.com/documentation/avfoundation/avcapturedevice/1390520-deviceswithmediatype

If you set "Treat Warnings as Error = no" and restart xCode it is only a warning and we only have to increase MacOs to 10.13 (which adds more compatible Macs). I tested it and also ran all the tests with success. 

My suggestion would be to keep this library as compatible as possible. But that is a decision of the library owners, I guess. :)

2023-08-01 07:29 UTC, KBEMobisys commented on README.md
Could you also update the Ruby example "platform :ios, '8.0'" in the Readme?

Add also the "s.ios.deployment_target" and "s.osx.deployment_target" in the podspec file?

2023-08-01 07:32 UTC, KBEMobisys requested changes
Appreciate your work :)

I added some new comments in Pullrequest.

2023-09-06 18:04 UTC, adil-hussain-84 commented
@kenstir Are you able to make the change to the "s.ios.deployment_target" and "s.osx.deployment_target" values in the "ZXingObjC.podspec" file as requested by @KBEMobisys in the pull request [here](https://github.com/zxingify/zxingify-objc/pull/575/files/a2aa6bc1a03e629bf76c1ed32c9da7f1ed4b1c1f#r1280215032)?

2023-09-12 01:23 UTC, kenstir commented on README.md
Done!  Sorry it took so long, I got distracted.

2023-09-12 01:24 UTC, kenstir reviewed
self check: pass

2023-09-29 08:03 UTC, ale-gen commented
Hey, these changes are exactly what I'm waiting for! When can I expect to bump deployment target to keep Xcode 14 happy?

2023-10-02 08:56 UTC, KBEMobisys approved these changes

2023-10-02 08:59 UTC, KBEMobisys commented
@adil-hussain-84 Could you review the pull request again? And are you able to merge it or who can do this??
Would be great to finalize this soon :)

2023-10-02 11:23 UTC, adil-hussain-84 commented
@KBEMobisys: Sadly I don't have write access 🙁 I'm hoping one of the individuals listed in the [Kudos](https://github.com/zxingify/zxingify-objc#kudos) section of the project's README file (@cwalcott and/or @neacao perhaps) can review the MR 🙏

2023-10-02 11:23 UTC, adil-hussain-84 approved these changes

2023-10-02 13:07 UTC, KBEMobisys commented
@benjohnde @tknoelle You are members of [zxingify](https://github.com/zxingify). Could you review and merge this PR?

We would love to see a new release with this change, so zxingify is compatible to Xcode 14.3 and above.

2023-10-04 21:41 UTC, benjohnde commented
> @benjohnde @tknoelle You are members of [zxingify](https://github.com/zxingify). Could you review and merge this PR?
> 
> We would love to see a new release with this change, so zxingify is compatible to Xcode 14.3 and above.

Sry for the delay, I can merge it tomorrow and also prepare a cocoapods release.

2023-10-05 14:56 UTC, merged

2023-10-06 09:22 UTC, adil-hussain-84 commented
Thank you so much @benjohnde for merging in the pull request and performing the release 🙏 We were starting to fear the worst that we'd have to fork this repository and maintain the fork.